### ISSUE TITLE
[Combat] Update the armour penalties to automatically pull through

### ISSUE THREAD

**Issue by LeeRhodes** [LeeRhodes/roll20-character-sheets#1]
Investigate adding the armour penalties to the state, using the "on change" logic.

**Comment by Seraaron** [comment]
On the topic of armour: It would be great if each body section had it's own skill-box with an associated rolling macro, rather than the dots thing that's there at the moment. So that you can name shade and exponent of each piece like a skill, so it says like 'left steel grieve: B3' and then the box that you click to roll. 

Ideally (and I know this might be asking a bit much) but ideally the armour 'skill' would not be affected by wounds, and the macro dialogue box could ask you what the opponents VA is, rather than the Ob (since the Ob is always 1 + VA). Additionally you could have one of those circle entries too, like for 'Tax', so that you can track how damaged the armour gets.

**Comment by LeeRhodes** [comment]
Oh I like that Idea, shouldn't be hard to do. 👍

**Comment by LeeRhodes** [comment]
@Seraaron 
<img width="1359" alt="screen shot 2018-11-02 at 16 51 08" src="https://user-images.githubusercontent.com/19798820/47928953-97b2d700-debf-11e8-9497-bbe107ac0a0d.png">
Something Along these lines?

**Comment by Seraaron** [comment]
YES, omg that would be perfect! :D

Thank for the quick response, and sorry for the slow response an my end. I keep forgetting to check my emails.

**Comment by LeeRhodes** [comment]
<img width="775" alt="screen shot 2018-11-09 at 14 07 41" src="https://user-images.githubusercontent.com/19798820/48266989-ef55c300-e428-11e8-87d4-f2353a5385ca.png">
Just finishing the VA = obstacle then I am done :)

**Comment by Seraaron** [comment]
Awesome. :D
Just remember that it's 1 + VA = Ob. (See pg 476)

**Comment by LeeRhodes** [comment]
Yep that's how it works, just need to raise the request to get it added 👍

**Comment by LeeRhodes** [comment]
@Seraaron the armour change is now in the live sheet :)

**Comment by LeeRhodes** [comment]
Closing this and will work on the pulling through of penalties in a separate issue.
