### ISSUE TITLE
[Skills] Auto adding and Deducting Artha from a roll

### ISSUE THREAD

**Issue by LeeRhodes** [LeeRhodes/roll20-character-sheets#4]

**Comment by Seraaron** [comment]
I'm not sure that this is a good idea, because "Artha dice" can come from more places than just Persona. When a Deeds point is used to double base dice for example, they all count as Artha dice. If the logic is too simplified then adding +5 to the Artha section, say, might end up deducting 5 Persona instead of 1 Persona and 1 Deeds, for example. 
I know that manually tracking Artha expenditure is an extra step of manual bookeeping, but it's a set of thought processes that are a lot easier for a human to execute than it is for machine logic to handle, imo.
I'm not saying it's impossible, but that it's a lot of work for very little gain. 
Plus part of the fun is in getting to subtract and add it yourself and watch those number go up. :)

**Comment by LeeRhodes** [comment]
Sorry being busy with new job. The idea being this @Seraaron was that there are 2 types are artha you use for before rolling, Persona or Deeds (When it comes to adding dice) the idea would be to ask "are you spending persona and/or a deed, type in number of persona. We know all you can do with a deed is double the exponent so it would be easy to handle that. then it would just deduct based on that. It was a minor issue yes, but question I always ask. If you are doing something more than 3 times, maybe there is a better way of doing this. :)

**Comment by LeeRhodes** [comment]
@Seraaron sorry being busy with new job, can get back on these now :) . But the idea behind this was: we know for adding new dice there are only 2 types of artha we use: Deeds and/or Persona. You would either mark it as using a deed, then we can double the exponent automatically and offer the option of adding up to 3 persona. But yes it is mostly a quality of life change. Mostly this is because I always ask myself the question: If you are manually doing something more than 3 times, is there a better way of doing it. I agree I don't want to remove manual interaction entirely but would be a nice aid.

**Comment by LeeRhodes** [comment]
Retroactive rolls I would just ignore, this that would require a massive changes to how rolls are done. But the 2 other options I have not looked at are spending fate to remove obstacles and persona for wounds. But again would require some rethinking on how to display these, so putting on the back burner for now.

**Comment by Seraaron** [comment]
That's not true though @LeeRhodes, that's not the only use of Deeds. Deeds can add dice equal to your Grief or Hatred exponent, which is sometimes better than doubling your base dice pool. Or spending a persona point for Greed can do the same thing too (not sure why it's cheaper for dwarfs to get the same effect, but that's the way it is). Plus you can be awarded Artha dice from other sources too. It's a houserule, granted, but I will occasionally grant players a free artha die for good ideas. It's not persona though, because it doesn't count towards an epiphany. 
I think it works much better as is. Just asking how many artha dice you want to add.

**Comment by LeeRhodes** [comment]
Oh yeah forgot about emotional stats. This was mostly noticed from my own play groups. Yep I am happy with keeping it simple. :)
